"""SQLAlchemy 2.0 ORM models for the AI Recruitment Suite.

All models use the modern typed ``Mapped`` / ``mapped_column`` style
introduced in SQLAlchemy 2.0. This gives static-analysis tools (mypy, pyright)
visibility into column types and makes the ORM declarations self-documenting.

Models
------
* ``User`` — recruiters and candidates (role-based).
* ``JobRequirement`` — a posted job, generated by an LLM or created manually.
* ``InterviewQuestion`` — a bank of questions attached to a job.
* ``InterviewSession`` — a candidate's interview conversation state.

Key design decisions
--------------------
* **UUID primary keys** — UUIDs are globally unique, non-sequential (so they
  don't leak row counts), and safe to generate client-side. We use
  ``uuid.uuid4`` as the Python-side default; Postgres also has
  ``gen_random_uuid()`` but generating in Python avoids a round-trip.
* **Postgres-native types** — ``JSONB`` (not ``JSON``) for structured
  metadata because ``JSONB`` supports GIN indexes and binary comparison;
  ``ARRAY(String)`` for keywords because it avoids a join table for a
  simple list of strings.
* **Enum columns** — ``UserRole`` and ``QuestionCategory`` use Python
  ``enum.Enum`` mapped to Postgres ``ENUM`` types. This gives DB-level
  constraint (invalid values are rejected at insert) and Python-level
  type safety.
* **Cascade delete** — ``JobRequirement.questions`` uses
  ``cascade="all, delete-orphan"`` so deleting a job automatically deletes
  its question bank, preventing orphaned questions.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import Any, Optional

from sqlalchemy import (
    ARRAY,
    Boolean,
    DateTime,
    Enum as SAEnum,
    Float,
    ForeignKey,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PGUUID
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    relationship,
)


# ---------------------------------------------------------------------------
# Declarative base
# ---------------------------------------------------------------------------

class Base(DeclarativeBase):
    """Shared declarative base for all ORM models.

    Using ``DeclarativeBase`` (SQLAlchemy 2.0) instead of the legacy
    ``declarative_base()`` function gives better type inference and
    supports ``Mapped`` type annotations natively.
    """


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class UserRole(enum.Enum):
    """User role for authorization.

    Stored as a Postgres ``ENUM`` so the DB enforces valid values.
    """

    recruiter = "recruiter"
    candidate = "candidate"


class QuestionCategory(enum.Enum):
    """Interview question category.

    The LLM is asked to produce questions across these three categories.
    If the model returns an unexpected string, the router normalizes it
    to ``technical`` (see ``app/routers/recruitment.py``) rather than
    dropping the question.
    """

    technical = "technical"
    behavioral = "behavioral"
    experience = "experience"


# ---------------------------------------------------------------------------
# User
# ---------------------------------------------------------------------------

class User(Base):
    """A recruiter or candidate.

    ``hashed_password`` is stored (never plaintext) but is **never** exposed
    in API responses — the Pydantic schemas in ``app/schemas.py`` omit it.
    Auth/JWT wiring is out of scope for this pass; the column exists so
    the schema is ready for a future auth middleware.
    """

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        index=True,
        nullable=False,
    )
    hashed_password: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    full_name: Mapped[str] = mapped_column(String(255), nullable=False)
    role: Mapped[UserRole] = mapped_column(
        SAEnum(UserRole, name="user_role", create_constraint=True),
        nullable=False,
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        default=True,
        nullable=False,
    )
    # ``profile_data`` stores arbitrary candidate metadata (resume text,
    # extracted skills, etc.) as a JSONB blob. JSONB is preferred over JSON
    # because it stores a binary representation that supports indexing and
    # efficient key/value lookups.
    profile_data: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    # Jobs created by this user (recruiter).
    created_jobs: Mapped[list["JobRequirement"]] = relationship(
        back_populates="created_by_user",
        foreign_keys="JobRequirement.created_by",
    )

    # Interview sessions where this user is the candidate.
    interview_sessions: Mapped[list["InterviewSession"]] = relationship(
        back_populates="candidate",
        foreign_keys="InterviewSession.candidate_id",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<User id={self.id} email={self.email!r} role={self.role}>"


# ---------------------------------------------------------------------------
# JobRequirement
# ---------------------------------------------------------------------------

class JobRequirement(Base):
    """A posted job requirement.

    Can be created manually or generated by the LLM from a short prompt
    (see ``POST /api/v1/jobs/generate``). The ``chroma_doc_id`` links the
    Postgres row to its ChromaDB vector document for semantic search.
    """

    __tablename__ = "job_requirements"

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    # Postgres ``ARRAY(String)`` — avoids a join table for a simple list
    # of keyword strings. Supports GIN index for ``&&`` (overlap) queries.
    keywords: Mapped[list[str]] = mapped_column(
        ARRAY(String),
        nullable=False,
        default=list,
    )
    # Arbitrary metadata (salary range, location, experience level, etc.).
    extra_metadata: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    # The ChromaDB document id returned when the job is indexed. Stored so
    # we can query Chroma by this id for job-restricted vector similarity.
    chroma_doc_id: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
    )
    created_by: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    created_by_user: Mapped[Optional[User]] = relationship(
        back_populates="created_jobs",
        foreign_keys=[created_by],
    )

    # Cascade delete: deleting a job deletes all its questions.
    questions: Mapped[list["InterviewQuestion"]] = relationship(
        back_populates="job",
        cascade="all, delete-orphan",
        order_by="InterviewQuestion.created_at",
    )

    # Interview sessions for this job.
    interview_sessions: Mapped[list["InterviewSession"]] = relationship(
        back_populates="job",
        foreign_keys="InterviewSession.job_id",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<JobRequirement id={self.id} title={self.title!r}>"


# ---------------------------------------------------------------------------
# InterviewQuestion
# ---------------------------------------------------------------------------

class InterviewQuestion(Base):
    """A single interview question attached to a job's question bank.

    Generated by the LLM via ``POST /api/v1/jobs/{job_id}/questions``.
    The ``category`` enum drives the distribution of question types.
    """

    __tablename__ = "interview_questions"

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    job_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("job_requirements.id", ondelete="CASCADE"),
        nullable=False,
    )
    question_text: Mapped[str] = mapped_column(Text, nullable=False)
    category: Mapped[QuestionCategory] = mapped_column(
        SAEnum(QuestionCategory, name="question_category", create_constraint=True),
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    job: Mapped[JobRequirement] = relationship(
        back_populates="questions",
        foreign_keys=[job_id],
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<InterviewQuestion id={self.id} category={self.category}>"


# ---------------------------------------------------------------------------
# InterviewSession
# ---------------------------------------------------------------------------

class InterviewSession(Base):
    """A candidate's interview conversation for a specific job.

    The ``chat_history`` JSONB array stores the full conversation as a
    list of ``{"role": "assistant"|"user", "content": "..."}`` objects.
    This is the single source of truth for the conversation — we don't
    normalize each turn into a separate row because:

    1. The conversation is always read/written as a unit (append a turn,
       then read the whole history for the next LLM call).
    2. JSONB supports efficient partial updates via ``jsonb_set``.
    3. Normalizing into rows would add a join on every turn, increasing
       latency for no query flexibility benefit.

    ``final_score`` is the average of all per-turn scores, computed once
    the question bank is exhausted (``is_complete = True``).
    """

    __tablename__ = "interview_sessions"

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    candidate_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    job_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("job_requirements.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Array of {"role": "assistant"|"user", "content": "..."} objects.
    chat_history: Mapped[list[dict[str, str]]] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
    )
    final_score: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )
    feedback: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    is_complete: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    candidate: Mapped[User] = relationship(
        back_populates="interview_sessions",
        foreign_keys=[candidate_id],
    )

    job: Mapped[JobRequirement] = relationship(
        back_populates="interview_sessions",
        foreign_keys=[job_id],
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<InterviewSession id={self.id} "
            f"candidate={self.candidate_id} job={self.job_id} "
            f"complete={self.is_complete}>"
        )